export function runInstanceChecks(): void {
    print('Instance checks')
    WebRequest.get('https://httpbin.org/get', (request) => {
        print('Get 1')
        print(request.download_progress)
        print(request.error)
        print(request.is_error)
        print(request.is_done)
        print(request.response_code)
        print(request.text)
        print(request.upload_progress)
        print(request.url)
        print(request.getResponseHeader('noexist'))
        print(request.getResponseHeaders())
        print('End get 1')
    })
    WebRequest.get('https://httpbin.org/response-headers?freeform=testfree', (request) => {
        print('Get 2')
        print(request.download_progress)
        print(request.error)
        print(request.is_error)
        print(request.is_done)
        print(request.response_code)
        print(request.text)
        print(request.upload_progress)
        print(request.url)
        print(request.getResponseHeader('freeform'))
        print(request.getResponseHeaders())
        print('End get 2')
    })
    // Valid but throws error because i dont understand how dispose works
    // let request = WebRequest.get('https://httpbin.org/image/jpeg', (request) => {
    //     print('Get should be disposed')
    //     print(request.download_progress)
    //     print(request.error)
    //     print(request.is_error)
    //     print(request.is_done)
    //     print(request.response_code)
    //     print(request.text)
    //     print(request.upload_progress)
    //     print(request.url)
    //     print(request.getResponseHeader('noexist'))
    //     print(request.getResponseHeaders())
    //     print('End get should be disposed')
    // })
    // request.dispose()
}
